language: node_js
node_js:
  - '8'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn install
  - yarn lint
  - yarn run build
after_script: greenkeeper-lockfile-upload
cache:
  yarn: true
  directories:
    - node_modules
